version: "3.9"

services:
  auth:
    image: registry.problemka-mtuci.tech/auth:dev
    env_file:
      - .env.dev
    ports:
      - "8001:8000"
    restart: always

  reports:
    image: registry.problemka-mtuci.tech/reports:dev
    env_file:
      - .env.dev
    ports:
      - "8002:8000"
    restart: always

  notification:
    image: registry.problemka-mtuci.tech/notification:dev
    env_file:
      - .env.dev
    ports:
      - "8003:8000"
    restart: always
