apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: registry.problemka-mtuci.tech/auth:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: problemka-env
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: dev
spec:
  selector:
    app: auth
  ports:
    - port: 8000
      targetPort: 8000
